name: Node.js Package

on:
  release:
    types: [created]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm i -g @antfu/ni
            - run: npm i -g pnpm
            - run: nci
            - run: nr ci:readme
            - run: cd packages/lib
            - run: pnpm publish --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
